import React from 'react';

function Hero() {
  return (
    <div className="flex items-center justify-center h-screen bg-[#1A4568]">
      <div className="text-center">
        <h1 className="text-5xl text-white font-bold">Lotte Avenue</h1>
        <p className="text-xl mt-4">
          <span className="text-white font-thin">Insert tagline here</span>
        </p>
      </div>
    </div>
  );
}

export default Hero;